<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_IntroductionChalkTalk OverviewSun Dec 1_7aa45a</name>
   <tag></tag>
   <elementGuidId>507dd2ed-2257-42ac-89a8-98d0df0281f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scroll-container']/div/div/div/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Cardstyle__CardWrapper-uohoe1-1.JQgkZ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f86d6e97-5a88-45d6-a869-2db7b551e8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Cardstyle__CardWrapper-uohoe1-1 JQgkZ</value>
      <webElementGuid>7bd982f5-9a96-4ea7-a23e-83fa76963383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IntroductionChalkTalk OverviewSun Dec 12, 2021Up Next</value>
      <webElementGuid>9eb7d9cc-30dd-47ce-8be9-5354917d130b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scroll-container&quot;)/div[1]/div[1]/div[@class=&quot;DashboardSummarystyle__DashboardScheduleWrap-sc-1yhxfd1-23 jNljcQ&quot;]/div[@class=&quot;Cardstyle__ScheduleWidgetWrap-uohoe1-0 leHLHO&quot;]/div[@class=&quot;Cardstyle__CardListWrap-uohoe1-7 dzLsUh&quot;]/div[@class=&quot;Cardstyle__CardWrapper-uohoe1-1 JQgkZ&quot;]</value>
      <webElementGuid>e482f7c3-2669-45c3-bf5f-5e784ba12991</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll-container']/div/div/div/div/div/div[3]</value>
      <webElementGuid>e44cd911-8682-4d21-8ec8-ac41d1fe69f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/following::div[11]</value>
      <webElementGuid>c86f470f-4b4c-409b-bc70-7ea2e31f0d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Students'])[1]/following::div[12]</value>
      <webElementGuid>460f98ed-1d2a-430f-a9d7-616f3b73c0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]</value>
      <webElementGuid>cad2505b-8db1-4ef4-bc1e-1ebb3e72f4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'IntroductionChalkTalk OverviewSun Dec 12, 2021Up Next' or . = 'IntroductionChalkTalk OverviewSun Dec 12, 2021Up Next')]</value>
      <webElementGuid>5e0c5b22-c888-4ce3-8f49-b4e087ebfe2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
