<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout</name>
   <tag></tag>
   <elementGuidId>98a62776-53f9-48f4-ad6f-5913ecc48478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/div/div[3]/div/ul/li[6]/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.TopNavBarstyle__DropdownWrap-sc-494zmv-8.kLPRNH > div.TopNavBarstyle__DropdownItem-sc-494zmv-9.jdJRIw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8058db7a-8e07-4540-8e15-5e0c72aa72c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TopNavBarstyle__DropdownItem-sc-494zmv-9 jdJRIw</value>
      <webElementGuid>b642b045-e541-4503-b624-c3525b5dc6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>500654e7-9a54-4a73-9545-2ed9aba32956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;MainLayoutstyle__PrimaryLayout-sc-4v0j7z-0 kDiaKk&quot;]/div[@class=&quot;TopNavBarstyle__TopNavBarVertical-sc-494zmv-0 cQPuFJ&quot;]/div[@class=&quot;TopNavBarstyle__NavBarGroup-sc-494zmv-2 guKSiF&quot;]/div[@class=&quot;TopNavBarstyle__InfoUserGroup-sc-494zmv-7 bgqsZt&quot;]/ul[@class=&quot;TopNavBarstyle__NavBarPrimary-sc-494zmv-3 dyVWaH&quot;]/li[@class=&quot;TopNavBarstyle__NavBarItem-sc-494zmv-4 zUmsj&quot;]/div[@class=&quot;TopNavBarstyle__DropdownWrap-sc-494zmv-8 kLPRNH&quot;]/div[@class=&quot;TopNavBarstyle__DropdownItem-sc-494zmv-9 jdJRIw&quot;]</value>
      <webElementGuid>b1dbfbb1-3679-4470-877a-a9fa829bf382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/div/div[3]/div/ul/li[6]/div[3]/div</value>
      <webElementGuid>aa8e9122-546c-42e6-b479-599bf30fb302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[2]/following::div[1]</value>
      <webElementGuid>8b0e0275-a1b6-4b00-af02-5614873ea9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar'])[1]/following::div[10]</value>
      <webElementGuid>5ffca20c-2655-4799-bca5-bd4f258f36e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lessons'])[2]/preceding::div[25]</value>
      <webElementGuid>afa84d90-2899-4fcf-91aa-e9895b21125e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subjects'])[1]/preceding::div[25]</value>
      <webElementGuid>fe807e55-cfd8-41d6-8e5a-3b98d1404cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>23110b6f-7d06-45f5-a1e9-e7015ca88d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div[3]/div</value>
      <webElementGuid>e09703ef-accb-4b6e-a475-5e593a84f6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>623b175a-6b8a-44e2-8dcc-925eed30646e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
