<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>81bf029c-7c9a-47b6-87b3-2ca883b80134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70ca9506-8629-4c8a-ae8a-d40310c73a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e46a08dd-585a-414a-a505-acba3b6a3d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ef5522ba-2a4a-428b-bc89-68bd68c919ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Formstyle__FormInputStyled-sc-10ymb0f-0 gMtwHg input-text</value>
      <webElementGuid>e911dfcf-8223-4b12-8fb7-818e0f1b6991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9febe75c-a704-4f44-b0df-4bb1eb6efb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;Loginstyle__LoginContainerWrap-sc-1l3t9ue-0 xvRCx&quot;]/div[@class=&quot;Loginstyle__LoginBlockRight-sc-1l3t9ue-4 bfwnMm&quot;]/div[@class=&quot;Loginstyle__LoginItemWrap-sc-1l3t9ue-1 HiGWy&quot;]/div[@class=&quot;Loginstyle__LoginItem-sc-1l3t9ue-2 eIVxWh&quot;]/form[1]/div[@class=&quot;Formstyle__FormItem-sc-10ymb0f-10 efaCIe form-items&quot;]/div[@class=&quot;Formstyle__FormInputWrapperStyled-sc-10ymb0f-5 gnFpsW&quot;]/input[@class=&quot;Formstyle__FormInputStyled-sc-10ymb0f-0 gMtwHg input-text&quot;]</value>
      <webElementGuid>d5c6f0ad-5bc0-4efc-be1a-538d7cd3f82b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>6bdd4611-4998-4d50-ab4c-fb2ecdbd78e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/div/div/form/div[2]/div/input</value>
      <webElementGuid>a72671a1-ae81-40df-8fd0-b1334a87c8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>14638126-6076-49f3-9cf4-f44d80ce607f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @type = 'password']</value>
      <webElementGuid>6e0c4912-9210-4672-9c45-5ecaacc88d57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
