<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email or Username_email</name>
   <tag></tag>
   <elementGuidId>d6f6b241-20a4-430f-babe-abf0dc4641db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01504480-33d7-4f0f-9e34-6e0b61e3efe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d18bf288-a530-446a-8793-c04c889d0f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2294814a-98fe-447c-8ca9-9177213a83f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Formstyle__FormInputStyled-sc-10ymb0f-0 gMtwHg input-text</value>
      <webElementGuid>02c54e62-91bb-461a-9c72-aa1f4e8a393f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58a97e6d-e392-473c-8b84-434a57909f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;Loginstyle__LoginContainerWrap-sc-1l3t9ue-0 xvRCx&quot;]/div[@class=&quot;Loginstyle__LoginBlockRight-sc-1l3t9ue-4 bfwnMm&quot;]/div[@class=&quot;Loginstyle__LoginItemWrap-sc-1l3t9ue-1 HiGWy&quot;]/div[@class=&quot;Loginstyle__LoginItem-sc-1l3t9ue-2 eIVxWh&quot;]/form[1]/div[@class=&quot;Formstyle__FormItem-sc-10ymb0f-10 efaCIe form-items&quot;]/div[@class=&quot;Formstyle__FormInputWrapperStyled-sc-10ymb0f-5 gnFpsW&quot;]/input[@class=&quot;Formstyle__FormInputStyled-sc-10ymb0f-0 gMtwHg input-text&quot;]</value>
      <webElementGuid>152989a2-3010-4c9f-934d-4fce0353bbed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>2d503fa1-d787-41ae-bb4f-38fb5b2d0436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/div/div/form/div/div/input</value>
      <webElementGuid>112e46cd-5ab2-474d-ada9-e89206976aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>148ee7fc-0d5b-47ae-8bf8-22e512eeef6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'email']</value>
      <webElementGuid>a43340eb-45c3-4b61-a1ae-5ff529532053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
