<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>investor_label</name>
   <tag></tag>
   <elementGuidId>64f72a43-aaf8-474f-8f99-4fadb6faaf7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[.//span[text()='Investor']]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//label[.//span[text()='Investor']]</value>
      <webElementGuid>b3a5692c-59de-49d7-9377-3ccb4841a683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
