<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noInvestmentH2text</name>
   <tag></tag>
   <elementGuidId>c09cc2c0-fc0f-469a-81ec-04a7efcf4dec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'card-body')]//h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[contains(@class,'card-body')]//h2</value>
      <webElementGuid>45a53c3e-449b-4c93-9b4a-edb08f176a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
