<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>4d9d8f0d-1914-4d32-b87e-928722080866</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.NavigationBar--button.ant-btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f384c206-d857-4012-b531-665f4baf6505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>__typename</name>
      <type>Main</type>
      <value>ItemPropsNode</value>
      <webElementGuid>4ca9cc4b-aa4b-483d-982b-c6080f961bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86e1e4a5-bbce-46bb-b97a-55b1fe20cd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn NavigationBar--button ant-btn-secondary</value>
      <webElementGuid>3074ab65-d775-4d91-9ee0-4f52bd618620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login </value>
      <webElementGuid>9e2f139c-a8f1-4259-8327-a3f3759faa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;flex-column flex-grow&quot;]/div[@class=&quot;App&quot;]/div[@class=&quot;PageLayout&quot;]/header[1]/div[@class=&quot;NavigationBar--container&quot;]/div[@class=&quot;Container fluid Section NavigationBar padding-x-xs-1 padding-x-md-2 padding-x-xxl-0 flex-column-center&quot;]/section[@class=&quot;Container responsive NavigationBar--section flex-column justify-center&quot;]/nav[1]/div[@class=&quot;ant-row-flex ant-row-flex-space-between ant-row-flex-middle NavigationBar--row&quot;]/ul[@class=&quot;ant-menu NavigationBar--menu ant-menu-light ant-menu-root ant-menu-horizontal&quot;]/li[@class=&quot;ant-menu-item  no-border-hover&quot;]/a[1]/button[@class=&quot;ant-btn NavigationBar--button ant-btn-secondary&quot;]</value>
      <webElementGuid>a72984ab-ae5c-4e03-84bc-ec9ed975475c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>d51aa399-cbd1-47b8-8366-b8a693beddae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div/div/div/header/div/div/section/nav/div/ul/li[10]/a/button</value>
      <webElementGuid>df7a841a-57a0-4fa7-8b21-9e4b59a36a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='···'])[5]/following::button[1]</value>
      <webElementGuid>91f346f5-58f9-4fe6-a577-8c4eaf5d02b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::button[1]</value>
      <webElementGuid>47bf7c1f-42e0-4348-ab5e-6a4a4c581dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='···'])[6]/preceding::button[1]</value>
      <webElementGuid>b2b8334c-81b6-41f7-a209-6ee7f04e439c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>48f12955-8229-4327-9aa7-a6d4bcc202a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Login ' or . = 'Login ')]</value>
      <webElementGuid>9040757f-b28f-45df-84b9-bda59b4aa394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
