<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>businessNameInputField</name>
   <tag></tag>
   <elementGuidId>605022ee-7d68-4bcc-bd7f-e488f1c1682f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@data-qa-ref=&quot;text-input&quot;])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//textarea[@data-qa-ref=&quot;text-input&quot;])[1]</value>
      <webElementGuid>fd52b3f7-0190-4a88-911d-fea3c7a0519b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
