<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>a2473068-21c6-416d-aa67-71d2892996eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.m-button.m-signer-mobile-header-button.m-signature-request--header-next-button.whitelabel-primary-button.bg-cerulean.hc-white.hbg-castle-rock.c-white.progress-button.state-loading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f6d6f38-2c0b-41ca-a54f-d51e4208388e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-ref</name>
      <type>Main</type>
      <value>button-next</value>
      <webElementGuid>58c49221-9fc9-4756-93d0-05e3eb87ba57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-button m-signer-mobile-header-button m-signature-request--header-next-button whitelabel-primary-button bg-cerulean  hc-white hbg-castle-rock c-white progress-button state-loading</value>
      <webElementGuid>6b797c85-5deb-4bf8-bd76-c4cac1ea0c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-btn</name>
      <type>Main</type>
      <value>common</value>
      <webElementGuid>2496430c-eaef-44b1-987b-d0d07e85bd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e0050e6-d877-476c-803c-7f5da408ac8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c76289b5-9adc-4300-bd7b-af88de5273d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>7c229724-2f4e-4d80-a6dc-b72be802ff32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signer-mobile-application&quot;)/div[@class=&quot;is-desktop is-embedded is-loaded whitelabel-page&quot;]/div[@class=&quot;m-signer-mobile&quot;]/div[@class=&quot;m-signature-request&quot;]/div[1]/div[@class=&quot;m-fixed-container&quot;]/div[@class=&quot;m-signer-mobile-header nav light m-signature-request--header small&quot;]/div[@class=&quot;m-signature-request--header-nav-right&quot;]/button[@class=&quot;m-button m-signer-mobile-header-button m-signature-request--header-next-button whitelabel-primary-button bg-cerulean  hc-white hbg-castle-rock c-white progress-button state-loading&quot;]</value>
      <webElementGuid>334a7698-7222-4189-8891-c6368ea79007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Access or sell shares of private compa_8d6d9b/iframe_divdiv</value>
      <webElementGuid>9cc57891-7715-49e4-8147-c37293208d12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>d7e75b9f-3e1f-4c4a-a76e-f285b46b72e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signer-mobile-application']/div/div/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>ae0a75ba-d537-4bc8-8da7-acea7124b23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::button[1]</value>
      <webElementGuid>38baa4db-cf51-4a60-91a6-6d5113ad9669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to sign'])[1]/preceding::button[1]</value>
      <webElementGuid>1e0c9294-97ff-428f-83de-c6f4286636c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>341fdf8b-f906-429e-a676-79a3779d0200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>92f9daca-d55f-4993-aef8-1aaa049957c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
