<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel Investment</name>
   <tag></tag>
   <elementGuidId>99067429-da86-4253-99f7-ab07212e0332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.MyInvestmentsDetails--action-buttons.margin-bottom-1.margin-x-md-1-half.ant-btn-warning-secondary.ant-btn-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a854256f-735b-4938-9509-661fda525077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95f5e6fc-13c1-4379-a6f9-4af271608907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn MyInvestmentsDetails--action-buttons margin-bottom-1 margin-x-md-1-half ant-btn-warning-secondary ant-btn-lg</value>
      <webElementGuid>115e9182-7104-4ffc-be84-0ad788fbdf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel Investment</value>
      <webElementGuid>91101be2-f9dd-4a4c-8e78-dea71dc7e9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;flex-column flex-grow&quot;]/div[@class=&quot;App user-logged-in&quot;]/div[@class=&quot;PageLayout&quot;]/div[@class=&quot;PageLayout--body&quot;]/main[@class=&quot;PageLayout--content-no-banner&quot;]/div[@class=&quot;MyInvestmentsDetails false&quot;]/div[@class=&quot;Container fluid Content flex-column-center text-center padding-x-xs-2&quot;]/div[@class=&quot;Container fluid Content--content overflow-hidden flex-column justify-center text-center&quot;]/div[@class=&quot;Content--body&quot;]/div[@class=&quot;flex-column-align-center&quot;]/div[@class=&quot;flex-center flex-wrap full-width padding-top-1&quot;]/div[2]/button[@class=&quot;ant-btn MyInvestmentsDetails--action-buttons margin-bottom-1 margin-x-md-1-half ant-btn-warning-secondary ant-btn-lg&quot;]</value>
      <webElementGuid>4c48f39c-a929-4275-af04-52185e5cb423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>570258e5-59af-4fc7-9b02-20ec5eb1d157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div/div/div/div/main/div/div[2]/div/div/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>908a06fc-19ad-458f-bf01-eefc1aa7cf0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete Investment'])[2]/following::button[1]</value>
      <webElementGuid>705dd55e-9cdd-4f3f-9d78-0a8ad06e52e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live DDD Palantir'])[1]/following::button[2]</value>
      <webElementGuid>8ea917c4-13fb-4cb7-8b48-9195192eb717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investment Status'])[1]/preceding::button[1]</value>
      <webElementGuid>dbffdd9a-14d0-42ee-91ee-f1ea71bed64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>219c93a2-59f4-4eeb-8f2d-624a00d762b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Cancel Investment' or . = 'Cancel Investment')]</value>
      <webElementGuid>764c4cef-df4b-4c8f-8107-625202e7be1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
