<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back to Transaction</name>
   <tag></tag>
   <elementGuidId>78ef3b0e-3bf0-467f-8bda-00eef3aeb07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.margin-top-3.ant-btn-primary.ant-btn-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e182ec2a-7435-4b14-ad62-f7e95ba3041c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3655cb9f-50fd-47a0-b078-8a56405e857e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn margin-top-3 ant-btn-primary ant-btn-lg</value>
      <webElementGuid>1b6e7aa3-05b8-43ab-af1e-8eeb410f2c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to Transaction</value>
      <webElementGuid>5f32aa76-f127-47f4-aa31-0d5c466bfe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[6]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap FullPageModal&quot;]/div[@class=&quot;ant-modal&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;flex-column full-width padding-y-2 padding-x-md-2 padding-x-xxl-0 margin-auto min-height-100vh max-width-sm padding-x-2 max-width-md&quot;]/button[@class=&quot;ant-btn margin-top-3 ant-btn-primary ant-btn-lg&quot;]</value>
      <webElementGuid>f6fc089a-779d-4863-8818-6b484c121e5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>0bb16829-257f-4fc9-811c-b8663fd75386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View details'])[2]/following::button[1]</value>
      <webElementGuid>095f327c-0f2c-404a-90fd-59445d18b32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[2]/following::button[1]</value>
      <webElementGuid>223fadfc-a53f-4e6f-9c5e-d5929f2cdcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>79e41ecd-ff57-4148-9a5a-64fb63c5db03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Back to Transaction' or . = 'Back to Transaction')]</value>
      <webElementGuid>86f23a3a-80fa-4a0d-afc0-2c40a48202b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
