<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>e55a7e9e-fe0a-4546-8ff1-ff841c751f73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.m-button.bg-cerulean.hc-white.border-1-cerulean.hborder-1-cerulean.hbg-cerulean.c-white.progress-button.state-loading</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;signer-mobile-application&quot;)/div[@class=&quot;is-desktop is-embedded is-loaded whitelabel-page&quot;]/div[@class=&quot;m-signer-mobile&quot;]/div[@class=&quot;m-signature-request-preview&quot;]/div[@class=&quot;m-signature-request-preview--test-warning&quot;]/div[@class=&quot;m-signature-request-preview--test-warning--content&quot;]/button[@class=&quot;m-button bg-cerulean  hc-white border-1-cerulean hborder-1-cerulean hbg-cerulean c-white progress-button state-loading&quot;][count(. | //button[@class = 'm-button bg-cerulean  hc-white border-1-cerulean hborder-1-cerulean hbg-cerulean c-white progress-button state-loading' and @data-btn = 'common' and @type = 'button' and @tabindex = '0' and (text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/Page_Access or sell shares of private compa_8d6d9b/iframe_divdiv']) = count(//button[@class = 'm-button bg-cerulean  hc-white border-1-cerulean hborder-1-cerulean hbg-cerulean c-white progress-button state-loading' and @data-btn = 'common' and @type = 'button' and @tabindex = '0' and (text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/Page_Access or sell shares of private compa_8d6d9b/iframe_divdiv'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f11ead3d-3aa2-40fb-b8c5-755decd1f751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-button bg-cerulean  hc-white border-1-cerulean hborder-1-cerulean hbg-cerulean c-white progress-button state-loading</value>
      <webElementGuid>906e0f5d-61b1-4693-b398-c92c3f691f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-btn</name>
      <type>Main</type>
      <value>common</value>
      <webElementGuid>db73c82a-8ac9-4019-90a2-dc5b4c29ee39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4dd9b522-235e-4c36-8904-1874397108c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>846ff573-8e32-48ae-9b71-3fe67b72b2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>58c55b16-07bc-4831-a45e-19f71a184b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signer-mobile-application&quot;)/div[@class=&quot;is-desktop is-embedded is-loaded whitelabel-page&quot;]/div[@class=&quot;m-signer-mobile&quot;]/div[@class=&quot;m-signature-request-preview&quot;]/div[@class=&quot;m-signature-request-preview--test-warning&quot;]/div[@class=&quot;m-signature-request-preview--test-warning--content&quot;]/button[@class=&quot;m-button bg-cerulean  hc-white border-1-cerulean hborder-1-cerulean hbg-cerulean c-white progress-button state-loading&quot;]</value>
      <webElementGuid>235f111e-e528-446b-b5a6-c067972776ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>a331495d-5a0c-42a7-a2fe-414868e3b905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signer-mobile-application']/div/div/div/div[3]/div[2]/button</value>
      <webElementGuid>99891967-08e3-41c3-8c08-2db532a3c995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is not legally binding'])[1]/following::button[1]</value>
      <webElementGuid>1a5b42e8-b56a-4f5e-80d9-cf9812fe15de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to sign'])[1]/following::button[1]</value>
      <webElementGuid>7d34e52f-e66a-41ec-8703-2e2f6c8bc8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8463f3c0-6d85-4e77-bfce-c8b8a3ca5282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>456f7233-e8f6-4470-9d13-9eb2a393075b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
