<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Withdraw</name>
   <tag></tag>
   <elementGuidId>6e4138bd-fbf8-47f3-ac57-10317291cac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='Submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.width-auto.ant-btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd481bf4-1617-4e78-8773-b8fe3e159374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>df91ccc9-2ffc-4e3c-b290-1c7e5cb1a3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tn</name>
      <type>Main</type>
      <value>wizard-button-next</value>
      <webElementGuid>266d928c-0d30-4189-ba3b-2cc6afcfdb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1a4e30e-c85f-4c71-935e-aba6c045ee48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn width-auto ant-btn-primary</value>
      <webElementGuid>ac023923-7c5a-45de-bdd6-3896afab2f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Withdraw</value>
      <webElementGuid>e62b5783-c901-47f9-8d86-a95e6a51378c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;overflow-hidden&quot;]/div[6]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap FullPageModal&quot;]/div[@class=&quot;ant-modal&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;flex-column full-width padding-y-2 padding-x-md-2 padding-x-xxl-0 margin-auto min-height-100vh max-width-sm MyInvestmentCancel padding-x-xs-2&quot;]/div[@class=&quot;NewWizard padding-bottom-6&quot;]/div[@class=&quot;ModalFooterStepButtons full-width display-flex&quot;]/div[@class=&quot;ModalFooterStepButtons--right&quot;]/button[@class=&quot;ant-btn width-auto ant-btn-primary&quot;]</value>
      <webElementGuid>2899ec51-6416-498d-9ad6-b5643728d06d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='Submit']</value>
      <webElementGuid>be1cd13d-233b-458e-91c0-614538be8e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ineligible to sell via Express deals'])[1]/following::button[1]</value>
      <webElementGuid>9d252e46-bd8e-4fb5-97e4-2e9936e466fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can not wire funds in time'])[1]/following::button[1]</value>
      <webElementGuid>27a0ab83-3f64-4bc5-874e-c6666721d463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>0913bd7d-cc97-4c92-9662-4589aa294fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Withdraw' or . = 'Withdraw')]</value>
      <webElementGuid>09e063e4-f9da-4cfb-9549-e900fed6bc95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
