<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Insert</name>
   <tag></tag>
   <elementGuidId>004d4f62-7726-4ed6-82a2-64a2d3a1ac88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='signer-mobile-body']/div[4]/div/div/div/div[3]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.src-hellospa-foundation-control-button-button__button--3xui_.src-hellospa-foundation-control-button-button__button--3xui_.whitelabel-primary-button.src-hellospa-foundation-control-button-button__primary--3Guxx</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73a60a8c-b1f1-49d2-ba63-4003f929b22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-btn</name>
      <type>Main</type>
      <value>foundation</value>
      <webElementGuid>c07c5830-5f7d-4ba3-8904-b892b28078cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>src-hellospa-foundation-control-button-button__button--3xui_ src-hellospa-foundation-control-button-button__button--3xui_ whitelabel-primary-button src-hellospa-foundation-control-button-button__primary--3Guxx</value>
      <webElementGuid>0627b571-8c9b-46b3-a761-d6585128d8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-ref</name>
      <type>Main</type>
      <value>singing-modal--insert-btn</value>
      <webElementGuid>bf203e3a-549a-4437-8704-b9f255f17c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Insert</value>
      <webElementGuid>2c9af960-5e53-472f-a7dd-29011962ac1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signer-mobile-body&quot;)/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;hello-modal__overlay hello-modal__overlay--afterOpen&quot;]/div[@class=&quot;hello-modal__content hello-modal__content--signature-modal hello-modal__content--afterOpen&quot;]/div[@class=&quot;hello-modal signature-modal&quot;]/div[@class=&quot;hello-modal__footer&quot;]/div[@class=&quot;hello-modal__footer-buttons&quot;]/button[@class=&quot;src-hellospa-foundation-control-button-button__button--3xui_ src-hellospa-foundation-control-button-button__button--3xui_ whitelabel-primary-button src-hellospa-foundation-control-button-button__primary--3Guxx&quot;]</value>
      <webElementGuid>85e4054e-895c-4c82-969a-e7affe883040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Access or sell shares of private compa_8d6d9b/iframe_divdiv</value>
      <webElementGuid>1378f736-d1a4-42ab-af26-b99844ab605c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='signer-mobile-body']/div[4]/div/div/div/div[3]/div[2]/button</value>
      <webElementGuid>63285a9d-d1e5-44b1-83d3-659c9a5c99af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change font'])[1]/following::button[1]</value>
      <webElementGuid>0f6ccfa2-a5d2-4665-a31f-cb97a27a4163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type it in'])[1]/following::button[2]</value>
      <webElementGuid>5356c8fc-46b1-4074-a998-9b04e4427ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Insert']/parent::*</value>
      <webElementGuid>9abfbc53-e882-41ee-a20a-99a04c150ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>d6a2256d-2b2b-4712-94b4-265de19b474f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Insert' or . = 'Insert')]</value>
      <webElementGuid>a6bb9200-de86-4dc0-81f0-f7468a5d32e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
