<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>172386f1-8131-491b-be9c-482067e1f3c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.m-button.m-signer-mobile-header-button.m-signature-request--header-next-button.whitelabel-primary-button.bg-cerulean.hc-white.hbg-castle-rock.c-white.progress-button.state-loading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54b52d51-2188-4787-99df-d13f8811dd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-ref</name>
      <type>Main</type>
      <value>button-next</value>
      <webElementGuid>2acef461-739d-4412-a9da-820db29f56ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-button m-signer-mobile-header-button m-signature-request--header-next-button whitelabel-primary-button bg-cerulean  hc-white hbg-castle-rock c-white progress-button state-loading</value>
      <webElementGuid>4d980c45-f1d6-4ee9-a28a-87de042aedf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-btn</name>
      <type>Main</type>
      <value>common</value>
      <webElementGuid>5f528999-e7de-4a0f-9f8d-a944af057718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bbed342-e700-420f-8fa6-78eb38509c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b16800e3-ecc6-4abf-b439-a1ab6f027cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>8c0d609a-54f9-41fe-87cd-990403c26915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signer-mobile-application&quot;)/div[@class=&quot;is-desktop is-embedded is-loaded whitelabel-page&quot;]/div[@class=&quot;m-signer-mobile&quot;]/div[@class=&quot;m-signature-request&quot;]/div[1]/div[@class=&quot;m-fixed-container&quot;]/div[@class=&quot;m-signer-mobile-header nav light m-signature-request--header small&quot;]/div[@class=&quot;m-signature-request--header-nav-right&quot;]/button[@class=&quot;m-button m-signer-mobile-header-button m-signature-request--header-next-button whitelabel-primary-button bg-cerulean  hc-white hbg-castle-rock c-white progress-button state-loading&quot;]</value>
      <webElementGuid>6487b9d5-0507-4abd-83b1-f7efaee0588d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Access or sell shares of private compa_8d6d9b/iframe_divdiv</value>
      <webElementGuid>8f2cad6b-3542-47c0-9629-62d33094a67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>1fc89d2a-fad3-4559-9228-b7c4c689cee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signer-mobile-application']/div/div/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>4d3cb8cc-ca92-4bb9-90dc-9b2c4d1ed522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::button[1]</value>
      <webElementGuid>e89392e1-d97c-4bc3-b55a-bdc6ddaac6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('You have completed all required fields. Please click ', &quot;'&quot;, 'Continue', &quot;'&quot;, '.')])[1]/preceding::button[1]</value>
      <webElementGuid>44adadd7-79d5-485d-9b2a-dc675c3990b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>cb307431-4e6d-4576-9520-dd8968826569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>3f22cd25-3219-4a54-8131-3a22c4f4124f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
