<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get Started</name>
   <tag></tag>
   <elementGuidId>9b6ab0d3-4e94-4dfe-9900-06547dd024fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.m-button.m-signer-mobile-header-button.m-signature-request-preview--get-started-button.whitelabel-primary-button.bg-cerulean.hc-white.hbg-castle-rock.c-white.progress-button.state-loading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b200d6a-55d7-4dd1-9460-7dd997bba455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-button m-signer-mobile-header-button m-signature-request-preview--get-started-button whitelabel-primary-button bg-cerulean  hc-white hbg-castle-rock c-white progress-button state-loading</value>
      <webElementGuid>d1db7200-5877-44b0-be1d-acb0e9b3c91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-btn</name>
      <type>Main</type>
      <value>common</value>
      <webElementGuid>51cc6fc8-ce31-422d-90ad-9023d0306c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce717765-e23f-4342-8063-f3ce5aa3efa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a9e04a51-32ad-48b8-8124-045c2f48c292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Started</value>
      <webElementGuid>fed8684c-7d07-4959-9275-c77048994a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signer-mobile-application&quot;)/div[@class=&quot;is-desktop is-embedded is-loaded whitelabel-page&quot;]/div[@class=&quot;m-signer-mobile&quot;]/div[@class=&quot;m-signature-request-preview&quot;]/div[@class=&quot;m-signer-mobile-header m-signature-request-preview--header whitelabel-header compact&quot;]/div[@class=&quot;m-signature-request-preview--right-container&quot;]/div[@class=&quot;m-signature-request-preview--get-started-button-container&quot;]/button[@class=&quot;m-button m-signer-mobile-header-button m-signature-request-preview--get-started-button whitelabel-primary-button bg-cerulean  hc-white hbg-castle-rock c-white progress-button state-loading&quot;]</value>
      <webElementGuid>9658a095-0b30-44e7-8f8d-215e01578b98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>465d8af4-6098-4195-b6ea-b5a756cfa98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signer-mobile-application']/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>2aafeee4-a19e-4db6-918f-817deb203fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POWERED BY'])[1]/preceding::button[1]</value>
      <webElementGuid>a0c18558-4072-43ed-9d8d-9d3110910f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fe225765-bfa4-4792-acad-a308506788e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Get Started' or . = 'Get Started')]</value>
      <webElementGuid>4f206c33-81cb-4dce-b33f-ed1c8a74ceb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
