<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next_src-hellospa-components-signature-_170626</name>
   <tag></tag>
   <elementGuidId>5b0bbec6-591c-4b9e-876c-64919084fce7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-0']/div/div[5]/div/div[2]/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2111622c-0fd6-4d75-b963-c2b23e3cc0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0ebe47ac-4e48-4799-b926-abc236256fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-ref</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f7edf89c-857d-4205-89cc-2d0a05560ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>src-hellospa-components-signature-request-display-field-checkbox__checkbox--2Jisj</value>
      <webElementGuid>90f524dc-4d3b-4955-8536-37bf72ec11db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-0&quot;)/div[@class=&quot;src-hellospa-components-signature-request-document-page__aspectContainer--16bsO&quot;]/div[@class=&quot;src-hellospa-components-signature-request-handle__handle--2XAfk src-hellospa-components-signature-request-handle__selected--2OL4j&quot;]/div[@class=&quot;src-hellospa-components-signer-signature-document-signer-field__signerField--o0kFD&quot;]/div[2]/label[1]/div[@class=&quot;src-hellospa-components-signature-request-display-field-checkbox__checkbox--2Jisj&quot;]</value>
      <webElementGuid>d3761c9d-c5e7-4ddc-a38c-9184659808d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Access or sell shares of private compa_8d6d9b/iframe_divdiv</value>
      <webElementGuid>5518b8ed-b284-4799-812e-9e29afee09c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-0']/div/div[5]/div/div[2]/label/div</value>
      <webElementGuid>bcfddbfd-ebf2-48d6-9c8a-dd88753b6ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/label/div</value>
      <webElementGuid>edecd591-87f4-4bb9-90a7-4faec7f4c2d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
