<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Click to sign</name>
   <tag></tag>
   <elementGuidId>c6f36310-f5f8-4672-b75d-9dc4d1dafa2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signature-6b86ce26a590e544b788c7ef945c81a8e6af395b___fa434b_30']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signature-6b86ce26a590e544b788c7ef945c81a8e6af395b___fa434b_30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26fbd0fc-f0d9-4ffd-a56e-f0cff56ea4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8321ec2d-3d2e-4aea-b001-eb169851dc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>src-hellospa-components-signer-signature-document-signature-placeholder__signaturePlaceholder--3mnGT</value>
      <webElementGuid>7409aa9a-c112-4078-a4a5-1f1cf8c917ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signature-6b86ce26a590e544b788c7ef945c81a8e6af395b___fa434b_30</value>
      <webElementGuid>f7231c6f-90d5-45a7-aa27-4755bf055240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-ref</name>
      <type>Main</type>
      <value>signature-input</value>
      <webElementGuid>1d45b04b-d602-4592-99e1-92f99ec9fa16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click to sign</value>
      <webElementGuid>9b58846d-d23a-4603-93ea-9c6d04fc872c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signature-6b86ce26a590e544b788c7ef945c81a8e6af395b___fa434b_30&quot;)</value>
      <webElementGuid>634c13a7-1de3-4710-ba4d-8630c50c4731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Access or sell shares of private compa_8d6d9b/iframe_divdiv</value>
      <webElementGuid>d0396cb9-6769-4eaf-aed9-46648b18197d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='signature-6b86ce26a590e544b788c7ef945c81a8e6af395b___fa434b_30']</value>
      <webElementGuid>e1460a55-6d32-4968-86b3-1d17a0f9a616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-0']/div/div[11]/div/div</value>
      <webElementGuid>ed42b467-09cb-40b5-babe-b9a41d7bfca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Req*'])[1]/following::div[67]</value>
      <webElementGuid>cdc36a10-b587-4da4-851c-da06abd38899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[68]</value>
      <webElementGuid>cf84597b-baed-4d07-99f6-8e0fef442a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'signature-6b86ce26a590e544b788c7ef945c81a8e6af395b___fa434b_30', '&quot;', ')')])[1]/preceding::div[25]</value>
      <webElementGuid>2546c4ce-f85a-4543-a9bc-aa4151b8be40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click to sign']/parent::*</value>
      <webElementGuid>27548418-9752-4c31-8023-7a688ce609d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div</value>
      <webElementGuid>09281832-62e3-478f-9555-be42762eb20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'signature-6b86ce26a590e544b788c7ef945c81a8e6af395b___fa434b_30' and (text() = 'Click to sign' or . = 'Click to sign')]</value>
      <webElementGuid>83ddc9df-96c4-45de-8c71-d2f56b0acb87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
