<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_5DocumentsAction Needed</name>
   <tag></tag>
   <elementGuidId>8b9df2ed-d67e-4a7a-bf7b-8ee2cb728f05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div/div/div/div/main/div/div[2]/div/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.SectionConfigPanel.padding-y-3.padding-x-2.border-bottom.flex-center.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ddd2c76-2966-4f93-a670-c1def62f1ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8323130d-037d-44e2-8380-443977b349c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84659f36-bfae-472f-8047-2fb0aee6edcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SectionConfigPanel padding-y-3 padding-x-2 border-bottom flex-center cursor-pointer</value>
      <webElementGuid>c79d517c-bbac-430a-a727-50aadead8b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5DocumentsAction Needed</value>
      <webElementGuid>9d91166d-8569-4f64-ab29-beb116f4670a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[@class=&quot;flex-column flex-grow&quot;]/div[@class=&quot;App user-logged-in&quot;]/div[@class=&quot;PageLayout&quot;]/div[@class=&quot;PageLayout--body&quot;]/main[@class=&quot;PageLayout--content-no-banner&quot;]/div[@class=&quot;margin-x-auto&quot;]/div[@class=&quot;background-color-light&quot;]/div[@class=&quot;max-width-md margin-x-auto&quot;]/div[@class=&quot;SectionConfigPanel padding-y-3 padding-x-2 border-bottom flex-center cursor-pointer&quot;]</value>
      <webElementGuid>9be19ffb-ed7e-4039-8614-680709cd4a1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div/div/div/div/main/div/div[2]/div/div[5]</value>
      <webElementGuid>809fae7d-f0f0-4650-82ca-95f9c8e4339a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[3]/following::div[1]</value>
      <webElementGuid>f2e00db2-8aca-4890-8e53-b5b9e9593418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concentration Limits'])[1]/following::div[2]</value>
      <webElementGuid>a8266668-64e7-43f4-a618-33cb0ca8bd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[5]</value>
      <webElementGuid>41a7d7ac-1b40-4cbc-a31a-a2f73e75ec47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '5DocumentsAction Needed' or . = '5DocumentsAction Needed')]</value>
      <webElementGuid>57d9586f-526d-4dd5-b109-aba4781882df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
