<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Add your signature_signature-modal-tab-b_db217b</name>
   <tag></tag>
   <elementGuidId>495f280b-f599-427b-b5a4-d36362aa3740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='signer-mobile-body']/div[4]/div/div/div/div[2]/div/ol/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>27e8ea68-2d4c-4312-8277-14cfdc81a480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type it in</value>
      <webElementGuid>1c122739-c38e-42a5-8c14-a649636e8a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa-ref</name>
      <type>Main</type>
      <value>signing-modal--T</value>
      <webElementGuid>77568295-15e0-4977-9db7-14e833b9b0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signature-modal-tab-bar__list-item</value>
      <webElementGuid>0490a061-a639-4b03-ba56-8bfb89a9f025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signer-mobile-body&quot;)/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;hello-modal__overlay hello-modal__overlay--afterOpen&quot;]/div[@class=&quot;hello-modal__content hello-modal__content--signature-modal hello-modal__content--afterOpen&quot;]/div[@class=&quot;hello-modal signature-modal&quot;]/div[@class=&quot;hello-modal__body hello-modal__body--scrollable&quot;]/div[@class=&quot;signature-modal-tab-bar&quot;]/ol[@class=&quot;signature-modal-tab-bar__list&quot;]/li[@class=&quot;signature-modal-tab-bar__list-item&quot;]</value>
      <webElementGuid>e4af0f19-94d2-4529-8bbf-0738ddb10517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Access or sell shares of private compa_8d6d9b/iframe_divdiv</value>
      <webElementGuid>3a5b0a3e-21fd-4877-8a75-bdac0b639b50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='signer-mobile-body']/div[4]/div/div/div/div[2]/div/ol/li[2]</value>
      <webElementGuid>175ecaf2-ff7c-4736-8c57-67a30b671fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add your signature'])[1]/following::li[2]</value>
      <webElementGuid>ffde8e3e-7374-412e-aeac-255a1bdf1d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to sign'])[1]/following::li[2]</value>
      <webElementGuid>4666e4c3-2c50-4ff9-840a-e9a718021685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draw it in'])[1]/preceding::li[2]</value>
      <webElementGuid>ffc33a4c-fbe4-4c19-a84c-c47be2625870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert'])[1]/preceding::li[2]</value>
      <webElementGuid>111a820b-45f3-4de4-b34c-995c2301437f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>b91c5abd-3f95-4d81-90c4-f55c32204181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@title = 'Type it in']</value>
      <webElementGuid>ca5f594a-49a5-4a95-8f60-8044f285b384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
