<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_I agree</name>
   <tag></tag>
   <elementGuidId>c0758247-9932-4f00-9eb4-d5e991288798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signer-mobile-application']/div/div/div/div/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.l-nowrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ce05cdf3-b772-429b-ae15-afe70168961e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l-nowrap</value>
      <webElementGuid>a6361361-a22c-48e9-951c-ac60fdd8a900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I agree</value>
      <webElementGuid>8b3f3b17-b51b-4695-8031-0986d7e192eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signer-mobile-application&quot;)/div[@class=&quot;is-desktop is-embedded is-loaded whitelabel-page&quot;]/div[@class=&quot;m-signer-mobile&quot;]/div[@class=&quot;m-signature-request-confirm&quot;]/div[@class=&quot;m-signer-mobile-header nav light m-signature-request-confirm--header&quot;]/div[@class=&quot;m-signature-request-confirm--subheader&quot;]/div[@class=&quot;m-signature-request-confirm--subheader-nav-right&quot;]/button[@class=&quot;m-button m-signer-mobile-header-button whitelabel-primary-button bg-cerulean  hc-white hbg-castle-rock c-white progress-button state-loading&quot;]/span[@class=&quot;l-nowrap&quot;]</value>
      <webElementGuid>ccb5c51f-97cb-45ef-9bf0-48634634c0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Access or sell shares of private compa_8d6d9b/iframe_divdiv</value>
      <webElementGuid>0222ec7a-9118-477c-8c6c-7f665dd5ba4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signer-mobile-application']/div/div/div/div/div/div/button/span</value>
      <webElementGuid>de320ce8-b32a-4e54-9709-69779f84557e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::span[1]</value>
      <webElementGuid>68f2d123-7c9a-4125-bba1-4b347d393b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HelloSign Terms of Service'])[1]/following::span[2]</value>
      <webElementGuid>9b2b3772-d19a-460b-8df5-c5da7ba82f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I agree']/parent::*</value>
      <webElementGuid>f2bee933-00c3-41bd-9f46-b4d9664e11d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>52d1bfc1-f6f0-40d6-b2ec-3c76b5f13cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'I agree' or . = 'I agree')]</value>
      <webElementGuid>4e64eb41-5b5b-467b-a9d8-acea914beebe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
