<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirmSkippingRecoveryMethodButton</name>
   <tag></tag>
   <elementGuidId>fcff2bfe-0944-4b87-ba90-871d13def36a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='Confirm']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[text()='Confirm']</value>
      <webElementGuid>4b283c16-2002-4f7b-b637-fd83ddeb6426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
