<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>freePlanWrapperDiv</name>
   <tag></tag>
   <elementGuidId>f625d427-640e-40c9-9c32-00631753dd3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='panel-group']/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@class='panel-group']/div[1]/div[1]</value>
      <webElementGuid>8c316597-1fca-4c65-8b75-536e97ab3ad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
