<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectFreePlanButton</name>
   <tag></tag>
   <elementGuidId>7118079c-cb39-47bb-bc2d-488094925236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='freePlan']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@id='freePlan']</value>
      <webElementGuid>76ee104b-85f1-42a9-9f4d-05ba7016b697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
