<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>userNameIframeWrapper</name>
   <tag></tag>
   <elementGuidId>c197cd3e-98fd-48e6-883c-24028d4a36c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@name=&quot;accountForm&quot;]/div/iframe</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//form[@name=&quot;accountForm&quot;]/div/iframe</value>
      <webElementGuid>9ecd03a9-c10a-4487-a1f3-4b0af2fb36a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
