<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>userNameInputForm</name>
   <tag></tag>
   <elementGuidId>fea9ba63-0596-4202-886e-cbe894fc95b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;username&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id=&quot;username&quot;]</value>
      <webElementGuid>43195684-685f-4011-9601-51a7617933a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
