<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select plan</name>
   <tag></tag>
   <elementGuidId>59ab9db1-773a-45ae-8f28-7d18239311e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.button-solid-norm.w100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77600e00-a16c-4641-bc3f-d5380dabf360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-solid-norm w100</value>
      <webElementGuid>58aef6d5-14a5-4f93-8f84-ae6ff7387af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e205f742-67db-4f8f-9741-05c51e7c778e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f789da4f-8869-4310-8585-d2435c08fbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>desc_Free</value>
      <webElementGuid>7c69af03-4f3d-4dab-a0e8-6fb977396ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select plan</value>
      <webElementGuid>cad780d5-b8d9-46fc-9634-03161f28ebe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;app-root&quot;]/div[@class=&quot;ui-prominent bg-norm color-norm h100 flex-no-min-children flex-nowrap flex-column h100 sign-layout-bg scroll-if-needed&quot;]/div[@class=&quot;pl2 pr2 sign-layout-container flex-item-fluid flex flex-nowrap flex-column flex-justify-space-between&quot;]/div[1]/main[@class=&quot;ui-standard color-norm bg-norm relative no-scroll w100 max-w100 center sign-layout&quot;]/div[@class=&quot;sign-layout-main-content&quot;]/div[@class=&quot;plan-selection mt1&quot;]/div[@class=&quot;border relative h100 plan-selection-plan p2&quot;]/button[@class=&quot;button button-solid-norm w100&quot;]</value>
      <webElementGuid>8114f092-49d8-4521-bbc3-6f55fa79a86e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>3bca4525-242b-4e38-a2c4-cba900fffaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/ month'])[1]/following::button[1]</value>
      <webElementGuid>5a65aa37-5f48-4066-b6f3-b068abcd9793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='—'])[1]/preceding::button[1]</value>
      <webElementGuid>42697070-6d78-4734-bd3a-7a39706fc652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select plan']/parent::*</value>
      <webElementGuid>eef2d628-e7e0-452b-8a02-6be4b23f20ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>a92e42c7-004f-4696-8bc1-e9620b58c5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Select plan' or . = 'Select plan')]</value>
      <webElementGuid>78989509-de2a-43f4-89a1-3282b83bf58c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
