<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SELECT FREE PLAN</name>
   <tag></tag>
   <elementGuidId>f33eaf9a-4a4a-41a1-b75d-b217d046a903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='freePlan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#freePlan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad1df8c9-b40c-406f-9a12-882f7b88b224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg pull-right</value>
      <webElementGuid>20a9f342-67c5-493e-a49f-4170077ab255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>freePlan</value>
      <webElementGuid>6d7174a2-7ece-4377-b541-bf52b6e95f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECT FREE PLAN</value>
      <webElementGuid>44e16e2a-ae84-4d4d-8481-c47be0861f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;freePlan&quot;)</value>
      <webElementGuid>714973c7-e2a3-461b-9ba2-fdc457b4f766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='freePlan']</value>
      <webElementGuid>85b5039d-f691-438a-a048-fb0ecea85205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='plan-free']/div[2]/div/div/button</value>
      <webElementGuid>8a2736fe-57c9-4e97-b7fe-b71ad80bda75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limited Support'])[1]/following::button[1]</value>
      <webElementGuid>d4cf0925-bfb2-461b-a6eb-66414048614a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FREE'])[2]/following::button[1]</value>
      <webElementGuid>dbd8b58e-ff84-44fe-9dd3-97da32376da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FREE'])[3]/preceding::button[1]</value>
      <webElementGuid>073cb44c-2fb8-4d3a-b7c6-db9eb5fa3bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade Anytime'])[1]/preceding::button[1]</value>
      <webElementGuid>9e44ed29-65ea-4ace-a86c-96b563eea620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SELECT FREE PLAN']/parent::*</value>
      <webElementGuid>606aaa1f-8439-4338-aaaf-6ed7ed55aba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>63599219-84e2-449a-96d4-dc6420a56d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'freePlan' and (text() = 'SELECT FREE PLAN' or . = 'SELECT FREE PLAN')]</value>
      <webElementGuid>4b83811f-4126-41f6-9011-3302cafcc192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
