<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>code_824821</name>
   <tag></tag>
   <elementGuidId>36859f58-5ee0-4310-b77d-2dd8cbe9a258</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Proton Verification Code'])[1]/following::code[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>68fd30d8-57a3-41ac-8184-03a57ace6a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>824821</value>
      <webElementGuid>e2cbaa95-7bf1-40bb-b767-e4e82d397aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;readdiv&quot;]/div[2]/p[1]/code[1]</value>
      <webElementGuid>2aeef445-d7b8-45c2-ab36-110faac817d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_Delete_message-frame</value>
      <webElementGuid>0c1f8548-caed-46cf-a0c8-578ac8435fa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proton Verification Code'])[1]/following::code[1]</value>
      <webElementGuid>27909923-c5b1-4b32-a873-d0d03d9d9a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/html[1]/body[1]/div[@class=', '&quot;', 'readdiv', '&quot;', ']/div[2]/p[1]/code[1]')])[1]/preceding::code[1]</value>
      <webElementGuid>9239ea4d-aaa1-4912-913d-6c5d427ff865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='824821']/parent::*</value>
      <webElementGuid>bfccfe29-161c-4f8f-9e99-dd15e6627e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//code</value>
      <webElementGuid>2ef59e11-08fc-4c94-8a8d-fb86c80c0601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//code[(text() = '824821' or . = '824821')]</value>
      <webElementGuid>30262b4a-9ad1-49bd-b81c-a756d4c2a648</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
