<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailIframe</name>
   <tag></tag>
   <elementGuidId>257462b0-e059-49ff-9ab1-d98a73f0094c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.w100.h-custom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>562a312f-3e1f-47a5-be87-e24eeeff28bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://account-api.protonmail.com/challenge/v4/html?Type=0&amp;Name=username</value>
      <webElementGuid>81353a7f-8ad5-455b-8ed4-9f658d328e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w100 h-custom</value>
      <webElementGuid>4746bb86-7c8f-48c6-94c9-2bcb142025e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-scripts allow-same-origin allow-popups</value>
      <webElementGuid>b17e45e0-5ffe-49b3-a03a-1c51d411bdb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;app-root&quot;]/div[@class=&quot;ui-prominent bg-norm color-norm h100 flex-no-min-children flex-nowrap flex-column h100 sign-layout-bg scroll-if-needed&quot;]/div[@class=&quot;pl2 pr2 sign-layout-container flex-item-fluid flex flex-nowrap flex-column flex-justify-space-between&quot;]/div[1]/main[@class=&quot;ui-standard color-norm bg-norm relative no-scroll w100 max-w100 center sign-layout mw30r&quot;]/div[@class=&quot;sign-layout-main-content&quot;]/form[1]/div[1]/iframe[@class=&quot;w100 h-custom&quot;]</value>
      <webElementGuid>d2099c71-4019-472b-b6d6-c1e116570a0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a76a5334-1872-43ea-8083-d6fe827a9356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://account-api.protonmail.com/challenge/v4/html?Type=0&amp;Name=username']</value>
      <webElementGuid>3042f1a2-ce17-43f7-a263-13c17dbdecf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
