<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailIfram</name>
   <tag></tag>
   <elementGuidId>5934b0ac-5b2d-4e80-b68a-9bc4c6ecea15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.w100.h-custom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9d5653d5-e7b6-4aa7-beeb-8c0f6d8b6859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://account-api.protonmail.com/challenge/v4/html?Type=0&amp;Name=username</value>
      <webElementGuid>7bd57691-a2d8-42fb-947f-e3374f9f5a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w100 h-custom</value>
      <webElementGuid>15384288-0d72-45a8-ad74-b1c931b8593b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-scripts allow-same-origin allow-popups</value>
      <webElementGuid>40db5862-e19f-42ee-99d4-9754e8b3c430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;app-root&quot;]/div[@class=&quot;ui-prominent bg-norm color-norm h100 flex-no-min-children flex-nowrap flex-column h100 sign-layout-bg scroll-if-needed&quot;]/div[@class=&quot;pl2 pr2 sign-layout-container flex-item-fluid flex flex-nowrap flex-column flex-justify-space-between&quot;]/div[1]/main[@class=&quot;ui-standard color-norm bg-norm relative no-scroll w100 max-w100 center sign-layout mw30r&quot;]/div[@class=&quot;sign-layout-main-content&quot;]/form[1]/div[1]/iframe[@class=&quot;w100 h-custom&quot;]</value>
      <webElementGuid>894c2ad2-c10b-4430-b8dd-8943f9771f9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3799c08a-a5b4-40aa-b53a-a932c654e08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://account-api.protonmail.com/challenge/v4/html?Type=0&amp;Name=username']</value>
      <webElementGuid>f562ba7d-bd2e-4f0c-bf91-c7fb9417496d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
