<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>freeTextSpan</name>
   <tag></tag>
   <elementGuidId>375e6c8c-e17b-49c1-948e-71aa2ce1bdcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='plan-free']/div[2]/div/div/span/h3/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3 > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>fed561e7-8faa-4d6a-9c0a-b45fa9586a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FREE</value>
      <webElementGuid>e3b9bbf4-fb15-4930-99e4-6f1538b46cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plan-free&quot;)/div[@class=&quot;panel-footer&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-md-offset-2 padding&quot;]/span[1]/h3[1]/strong[1]</value>
      <webElementGuid>d7fcc852-0689-461f-ab77-a6157c0687de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='plan-free']/div[2]/div/div/span/h3/strong</value>
      <webElementGuid>d430e609-db89-4dfc-9a9c-7b35f02bb442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT FREE PLAN'])[1]/following::strong[1]</value>
      <webElementGuid>ccb9cef6-1be7-4773-be19-2836e2e4ce4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limited Support'])[1]/following::strong[1]</value>
      <webElementGuid>7a6dd2ef-725e-4375-ac12-f964a70dc25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade Anytime'])[1]/preceding::strong[1]</value>
      <webElementGuid>efe2046c-5f84-4143-8cf8-1cc64dffd1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLUS'])[1]/preceding::strong[1]</value>
      <webElementGuid>45d64b95-c194-48ed-b845-74a347c3d1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/strong</value>
      <webElementGuid>e6484ed0-23c9-4470-8a3d-eb8dafe6f6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'FREE' or . = 'FREE')]</value>
      <webElementGuid>32c9006a-225d-40c1-b4e9-3cacc2360174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
