<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>getStartedButton</name>
   <tag></tag>
   <elementGuidId>613d1cea-366d-442a-a787-0251e61da7ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.button-large.button-solid-norm.w100.mb0-25</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c17a96c-9d9e-44a6-b580-44ca198df8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-large button-solid-norm w100 mb0-25</value>
      <webElementGuid>e8d4d694-dae7-4bec-9cee-c9bfb03317eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>74a0d89b-6ec7-47e5-b621-10f93f2e37ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0eb20334-0a46-45f2-beee-7a27b1dca60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus-fallback</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>df645608-e676-48e1-a20f-7d7fda2bb1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get started</value>
      <webElementGuid>047d9e23-e0a1-472f-8666-2e361bdb5039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;is-comfortable&quot;]/div[@class=&quot;modal-container&quot;]/dialog[@class=&quot;modal modal--intermediate modal--shorter-labels modal--no-outline outline-none&quot;]/form[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-content-inner&quot;]/div[@class=&quot;relative&quot;]/footer[@class=&quot;flex flex-nowrap flex-column&quot;]/button[@class=&quot;button button-large button-solid-norm w100 mb0-25&quot;]</value>
      <webElementGuid>69bd4ea1-99c2-4461-883f-8845707729d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>12c48572-df29-41b4-a177-4cf1c1536c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Proton'])[1]/following::button[1]</value>
      <webElementGuid>0ffa692a-2463-42b7-b57c-9d59d9910cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::button[1]</value>
      <webElementGuid>7e65da7f-55bc-4715-af78-27ab5aedbdbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to panel 0'])[1]/preceding::button[1]</value>
      <webElementGuid>7970a4d4-c4f9-432c-97fe-38c967fe6071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to panel 1'])[1]/preceding::button[2]</value>
      <webElementGuid>3663de58-3b46-4d0f-a2db-0cb6dc686fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get started']/parent::*</value>
      <webElementGuid>dc619466-45a3-4db0-8fc0-5a2fc7f100b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>17f44ce0-7965-4b87-bb7a-687aaab3dc97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Get started' or . = 'Get started')]</value>
      <webElementGuid>1f74d87f-2ec2-46b4-abf4-3832fd948e6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
