<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password must contain at least 8 characters</name>
   <tag></tag>
   <elementGuidId>fe301bc7-cd8d-43af-b1ec-97c16aff9b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id-3']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id-3 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f3ebeb9-08ac-44b1-a307-888c461374ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password must contain at least 8 characters</value>
      <webElementGuid>6a63af02-16a9-4728-b95a-bb86bfaaf08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-3&quot;)/span[1]</value>
      <webElementGuid>40399a91-ea06-4665-bbd6-e5639272765f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-3']/span</value>
      <webElementGuid>16338c74-bc5a-4a28-9ce0-831fb8f09a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeat password'])[1]/following::span[2]</value>
      <webElementGuid>5748fc9a-814a-4a59-90df-4f73137c5460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password must contain at least 8 characters'])[1]/following::span[3]</value>
      <webElementGuid>e455ed25-d7a3-4269-9c5d-386074410553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::span[1]</value>
      <webElementGuid>2abf64db-42bd-432d-b3e9-94502e844160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div[3]/span</value>
      <webElementGuid>5334edf6-0bce-4b77-b0c5-9a3118065202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Password must contain at least 8 characters' or . = 'Password must contain at least 8 characters')]</value>
      <webElementGuid>a1da0590-cbb8-4282-99e9-06724137d978</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
