<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continueInvistmentButton</name>
   <tag></tag>
   <elementGuidId>7844ee29-49b8-4d0c-8360-eab1ce11a095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[./span[text()='Continue']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[./span[text()='Continue']]</value>
      <webElementGuid>0ed37ee2-ef4b-489b-82fa-afafe63c0500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
