<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nextButtonSignupPage</name>
   <tag></tag>
   <elementGuidId>6a17f3bc-be5a-4c0c-9848-a0daef0fcc25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='Next']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[text()='Next']</value>
      <webElementGuid>5258b0ae-6788-4cab-9e1c-aed69be5c698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
