<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profileButton</name>
   <tag></tag>
   <elementGuidId>71a35b56-e818-48f5-8359-c1bc944d8cff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[contains(@class,'topnav-listItem')][last()]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//li[contains(@class,'topnav-listItem')][last()]/button</value>
      <webElementGuid>90d25912-35b9-47a8-b31d-4e7a0de5d908</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
