<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendEmailButton</name>
   <tag></tag>
   <elementGuidId>3edeae06-f452-419b-9924-9815cc3689e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[.//span[text()='Send']]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[.//span[text()='Send']]</value>
      <webElementGuid>fba8c84c-b94b-4374-b6fe-2aa8087d3500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
