<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newMessageWrapper</name>
   <tag></tag>
   <elementGuidId>a6a8437f-bb5e-4e5d-b733-b0b20ea5c54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'composer-container')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[contains(@class,'composer-container')]</value>
      <webElementGuid>c0e04d23-1b5d-4056-8c01-787acaf90804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
