<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailVerficationInputForm</name>
   <tag></tag>
   <elementGuidId>e1845bf0-b9c2-4cba-a4da-945944469a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='email']</value>
      <webElementGuid>c79eb738-157d-4dfd-ae49-24c167600e3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
