<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passwordInputForm</name>
   <tag></tag>
   <elementGuidId>7ee41015-d767-4b4d-b204-5d4b2db1d739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id=&quot;password&quot;]</value>
      <webElementGuid>d9cac6bd-4cf3-490b-a338-23c9c0794310</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
