<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailWrapperSpan</name>
   <tag></tag>
   <elementGuidId>8bc42d07-72fe-4a5d-a8e1-cbac575d7b4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='egen']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@id='egen']</value>
      <webElementGuid>a49ca077-71ec-4937-a10c-0df94c59ae8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
