<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>messageBodyIframe</name>
   <tag></tag>
   <elementGuidId>c626f2c6-fd9e-46ad-bed2-45f5279e5e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifmail']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//iframe[@id='ifmail']</value>
      <webElementGuid>09d7ed80-3afd-4bef-9b0c-0e0f4c83967d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
