<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>messageFromProtonMailWrapper</name>
   <tag></tag>
   <elementGuidId>9be235f1-e58c-4bcd-8a0c-bec7212f48c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Proton'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//span[text()='Proton'][1]</value>
      <webElementGuid>498f0c38-2e34-47e7-b77d-ece10e55136c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
