<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>randomEmailAddressGeneratorButton</name>
   <tag></tag>
   <elementGuidId>bc223d2f-29bc-4b11-8d97-519afff7bae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='listeliens']/a[contains(@href,'email-generator')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@id='listeliens']/a[contains(@href,'email-generator')]</value>
      <webElementGuid>39bc8bda-f125-4c1e-a553-8e0da59cd8a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
